first try
MarianMoskal/nodejs-homework-rest-api pull request #1
Opened 2021-11-25 18:32 UTC by MarianMoskal

Прошу проверить )

2021-11-25 21:23 UTC, KirillKulakow commented on app.js
> +app.use((_, res) => {
лучше в дальнейшем так не писать
используй понятные переменные и если они не нужны не нужно вместо них ничего придумывать

2021-11-25 21:27 UTC, KirillKulakow commented on model/handlerFunctions/removeContact.js
> +  const idx = contacts.findIndex(item => item.id === id)
лучше здесь item.id тоже преобразовывать в строку

2021-11-25 21:27 UTC, KirillKulakow commented on model/handlerFunctions/updateContact.js
> +  const idx = contacts.findIndex(item => item.id === id)
ид в строку

2021-11-25 21:31 UTC, KirillKulakow commented
инетересное решение добавить такие хэндлеры
но выполнение промисов внутри response - может иметь неожиданные последствия (как по мне)
но это сугубо личное мнение

2021-11-25 21:31 UTC, KirillKulakow requested changes
Need some fix

2021-11-25 22:50 UTC, MarianMoskal commented
> инетересное решение добавить такие хэндлеры но выполнение промисов внутри response - может иметь неожиданные последствия (как по мне) но это сугубо личное мнение

о каких именно идет речь? Кажется все как по тз делал. Ты имеешь ввиду что они могут не выполнится и будет ошибка? Как бы сделал ты в етом случае?

2021-12-01 19:51 UTC, KirillKulakow commented
В принципе ок (я перепроверил возможные ошибки), просто я такого интерфейса раньше не видел)

2021-12-01 19:51 UTC, KirillKulakow approved these changes

2021-12-01 21:43 UTC, merged