done
MarianMoskal/nodejs-homework-rest-api pull request #3
Opened 2021-12-25 19:04 UTC by MarianMoskal

2021-12-26 15:26 UTC, KirillKulakow commented on routeHandlers/contacts/getAll.js
> +  const { page = 1, limit = 20, favorite } = req.query
было бы неплохо делать проверку этих входящих параметров
все что приходит в req.query - это строка, поэтому такие параметры как page и limit нужно проверять на число и после преобразовывать
так же и с favorite - сначала проверка потом преобразовать в true или false
если данные не валидные - вернуть ошибку bad request

2021-12-26 15:29 UTC, KirillKulakow commented on routeHandlers/contacts/getAll.js
> +  if (favorite === 'true' || favorite === 'false') {
это жесткий костыль, можно сделать сразу поиск по фильтру
пример:
```
const filter = { owner: _id }
if (favorite !== undefined) {
  filter.favorite = favorite
}
const result = await Contact.find(
     filter, '', { skip, limit: Number(limit) }
   ).populate('owner', '_id name email')
```

2021-12-26 15:29 UTC, KirillKulakow requested changes
Need fix

2021-12-26 15:31 UTC, KirillKulakow commented
сделай еще выборки по удалению и редактированию только по контактам, которые принадлежат юзеру который сделал запрос

2021-12-28 20:34 UTC, KirillKulakow commented on package.json
> +    "node-boolify": "^1.0.6"
я у тебя в проекте не нашел использование данного пакета

2021-12-28 20:39 UTC, KirillKulakow commented on routeHandlers/contacts/getAll.js
> +const isBoolean = require('node-boolify').isBoolean
зачем оно тебе? это крах
удалить

2021-12-28 20:41 UTC, KirillKulakow commented on routeHandlers/contacts/getAll.js
> +  if (!Number(page) || !Number(limit) || (favorite !== undefined && !isBoolean(favorite))) {
можно написать
`if (!Number(page) || !Number(limit) || (favorite !== undefined && !["true", "false"].includes(favorite))) {`

2021-12-28 20:41 UTC, KirillKulakow commented on routeHandlers/contacts/getAll.js
> +    filter.favorite = favorite
здесь лучше написать `filter.favorite = favorite === "true"`

2021-12-28 20:43 UTC, KirillKulakow commented on routeHandlers/contacts/getById.js
> +  if (!data || data.owner.toString() !== _id.toString()) {
ужас - не делай так
ты же можешь просто сделать поиск по двум параметрам
`await Contact.findOne({ _id: id, owner: _id })`

2021-12-28 20:44 UTC, KirillKulakow commented on routeHandlers/contacts/put.js
> +  if (contact.owner.toString() !== _id.toString()) {
как и в прошлом комментарии

2021-12-28 20:44 UTC, KirillKulakow commented on routeHandlers/contacts/remove.js
> +  if (contact.owner.toString() !== _id.toString()) {
как и в прошлом комментарии

2021-12-28 20:44 UTC, KirillKulakow commented on routeHandlers/contacts/updateFavorite.js
> +  if (contact.owner.toString() !== _id.toString()) {
как и в прошлом комментарии

2021-12-28 20:45 UTC, KirillKulakow commented on routeHandlers/contacts/put.js
> +  if (contact.owner.toString() !== _id.toString()) {
тут можно совместить
await Contact.findOneAndUpdate({ _id: id, owner: _id }, body, { new: true })

2021-12-28 20:45 UTC, KirillKulakow requested changes
Need fix

2021-12-28 21:06 UTC, MarianMoskal commented on routeHandlers/contacts/getAll.js
> +    filter.favorite = favorite
Обьясни пожалуйста почему?

2022-01-04 20:07 UTC, KirillKulakow approved these changes

2022-01-04 20:07 UTC, merged