Hw05 avatars
MarianMoskal/nodejs-homework-rest-api pull request #4
Opened 2022-01-04 13:20 UTC by MarianMoskal

2022-01-04 20:15 UTC, KirillKulakow commented on routeHandlers/users/signup.js
> +  console.log(avatarURL)
удалить
в функцию gravatar нужно добавить опцию протокола
чтобы выводилась полная ссылка на картинку

2022-01-04 20:16 UTC, KirillKulakow commented on routeHandlers/users/updateAvatar.js
> +    const avatarURL = path.join('public', 'avatars', imageName)
было бы хорошо делать полную ссылку на картинку чтобы при переходе на нее выводилась картинка

2022-01-04 20:17 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
если будет интересно можешь добавить фильтрацию по типу файла
чтобы можно было загружать только картинки

2022-01-04 20:17 UTC, KirillKulakow requested changes
need fix

2022-01-04 21:16 UTC, MarianMoskal commented
не пойму в каком месте но некоторые картинки переворачивает на бок

2022-01-04 21:20 UTC, MarianMoskal commented
может из за маленького размера?

2022-01-04 23:15 UTC, KirillKulakow commented
подозреваю что в этом файле
https://github.com/MarianMoskal/nodejs-homework-rest-api/pull/4/files#diff-97d5bcf3aeeab6cf01d5c7d7d8372c4a504745671f9c4d4ab7007fe9b5fb3185

2022-01-05 10:38 UTC, MarianMoskal commented
Проблема с Jimp. Если картинка маленькая то все окей. Если большая то переворачивает на бок. Что можна с етим сделать?

2022-01-05 19:04 UTC, KirillKulakow approved these changes

2022-01-05 19:49 UTC, merged